# Generated by Django 4.1.1 on 2022-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('joining_date', models.DateTimeField(verbose_name='Joining date')),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=200)),
                ('performance_grade', models.IntegerField(default=0)),
            ],
        ),
    ]
