# Generated by Django 4.1.1 on 2022-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drftech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='performance_grade',
            new_name='performance_persent',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(verbose_name='salary'),
        ),
    ]
